/// <reference types="svelte" />
import { type Writable } from "svelte/store";
import type { Mode, SchemeCollection } from "./types";
import { PointTool } from "./point/point_tool";
import { PolygonTool } from "maplibre-draw-polygon";
import { RouteTool } from "route-snapper-ts";
import type { Position } from "geojson";
import { type UserSettings } from "./types";
export declare const gjSchemeCollection: Writable<SchemeCollection>;
export declare const pointTool: Writable<PointTool | null>;
export declare const polygonTool: Writable<PolygonTool | null>;
export declare const routeTool: Writable<RouteTool | null>;
export declare const hideSchemes: Writable<Set<string>>;
export declare const sidebarHover: Writable<number | null>;
export declare const mode: Writable<Mode>;
export declare function newFeatureId(gj: SchemeCollection): number;
export declare function deleteIntervention(id: number): void;
export declare function getArbitrarySchemeRef(schemeCollection: SchemeCollection): string;
export declare function setPrecision(pt: Position): Position;
export declare const userSettings: Writable<UserSettings>;
